spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 100
      hibernate.default_schema: ${storage.database.core-db.schema:public}

---
spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: local-dev

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${storage.database.core-db.url}
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 10000
      keepalive-time: 30000
      validation-timeout: 5000
      max-lifetime: 1800000 # 30분
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: dev

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${storage.database.core-db.url}
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 10000
      keepalive-time: 30000
      validation-timeout: 5000
      max-lifetime: 1800000 # 30분
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: prod

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${storage.database.core-db.url}
      username: ${storage.database.core-db.username}
      password: ${storage.database.core-db.password}
      maximum-pool-size: 5
      connection-timeout: 10000
      keepalive-time: 30000
      validation-timeout: 5000
      max-lifetime: 1800000 # 30분
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

